//!
//! generated by flatc-zig
//! schema:     reflection.fbs
//! typename    AdvancedFeatures
//!

pub const AdvancedFeatures = enum(u64) {
    none = 0,
    advanced_array_features = 1,
    advanced_union_features = 2,
    optional_scalars = 4,
    default_vectors_and_strings = 8,
};
