//!
//! generated by flatc-zig
//! schema:     reflection.fbs
//! typename    Enum
//!
//! Some added declarations.

const flatbuffers = @import("flatbuffers");
const std = @import("std");
const Types = @import("./lib.zig");

pub const Enum = struct {
    name: [:0]const u8,
    values: []Types.EnumVal,
    is_union: bool = false,
    underlying_type: Types.Type = .{},
    attributes: []Types.KeyValue,
    declaration_file: [:0]const u8,

    const Self = @This();

    pub fn init(allocator: std.mem.Allocator, packed_: PackedEnum) !Self {
        return .{
            .name = try packed_.name(),
            .values = try flatbuffers.unpackVector(allocator, Types.EnumVal, packed_, "values", true),
            .is_union = try packed_.isUnion(),
            .underlying_type = try Types.Type.init(try packed_.underlyingType()),
            .attributes = try flatbuffers.unpackVector(allocator, Types.KeyValue, packed_, "attributes", false),
            .declaration_file = try packed_.declarationFile(),
        };
    }

    pub fn deinit(self: Self, allocator: std.mem.Allocator) !void {
        allocator.free(self.attributes);
        allocator.free(self.values);
    }

    pub fn pack(self: Self, builder: *flatbuffers.Builder) !u32 {
        const field_offsets = .{
            .values = try builder.prependVectorOffsets(Types.EnumVal, self.values),
            .name = try builder.prependString(self.name),
            .attributes = try builder.prependVectorOffsets(Types.KeyValue, self.attributes),
            .documentation = try builder.prependVector([:0]const u8, self.documentation),
            .declaration_file = try builder.prependString(self.declaration_file),
        };

        try builder.startTable();
        try builder.appendTableFieldOffset(field_offsets.name);
        try builder.appendTableFieldOffset(field_offsets.values);
        try builder.appendTableField(bool, self.is_union);
        try builder.appendTableField(Types.Type, self.underlying_type);
        try builder.appendTableFieldOffset(field_offsets.attributes);
        try builder.appendTableFieldOffset(field_offsets.documentation);
        try builder.appendTableFieldOffset(field_offsets.declaration_file);
        return builder.endTable();
    }
};

pub const PackedEnum = struct {
    table: flatbuffers.Table,

    const Self = @This();

    pub fn init(size_prefixed_bytes: []u8) !Self {
        return .{ .table = try flatbuffers.Table.init(size_prefixed_bytes) };
    }

    pub fn name(self: Self) ![:0]const u8 {
        return self.table.readField([:0]const u8, 0);
    }

    pub fn valuesLen(self: Self) !u32 {
        return self.table.readFieldVectorLen(1);
    }
    pub fn values(self: Self, index: usize) !Types.PackedEnumVal {
        return self.table.readFieldVectorItem(Types.PackedEnumVal, 1, index);
    }

    pub fn isUnion(self: Self) !bool {
        return self.table.readFieldWithDefault(bool, 2, false);
    }

    pub fn underlyingType(self: Self) !Types.PackedType {
        return self.table.readField(Types.PackedType, 3);
    }

    pub fn attributesLen(self: Self) !u32 {
        return self.table.readFieldVectorLen(4);
    }
    pub fn attributes(self: Self, index: usize) !Types.PackedKeyValue {
        return self.table.readFieldVectorItem(Types.PackedKeyValue, 4, index);
    }

    pub fn documentation(self: Self) ![]align(1) [:0]const u8 {
        return self.table.readField([]align(1) [:0]const u8, 5);
    }

    pub fn declarationFile(self: Self) ![:0]const u8 {
        return self.table.readField([:0]const u8, 6);
    }
};
